Repository googleapis/java-servicedirectory, pull requests merged in 2020-06, with the labels that each got.

#72 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#75 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#78 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#80 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#86 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#90 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#94 chore: update README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#95 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-servicedirectory/pom.xml
  grpc-google-cloud-servicedirectory-v1beta1/pom.xml
  pom.xml
  proto-google-cloud-servicedirectory-v1beta1/pom.xml
Labels: cla: yes

#107 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#82 Adding java quickstart
  samples/snippets/src/main/java/com/example/servicedirectory/Quickstart.java
Labels: cla: yes
