Repository googleapis/java-servicedirectory, pull requests merged in 2020-11, with the labels that each got.

#215 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: servicedirectory, automerge, cla: yes

#216 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: servicedirectory, automerge, cla: yes, context: full

#218 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: servicedirectory, automerge, cla: yes

#219 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: api: servicedirectory, automerge, cla: yes, context: full

#225 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: servicedirectory, automerge, cla: yes

#226 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: servicedirectory, automerge, cla: yes, context: full

#232 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: servicedirectory, automerge, cla: yes

#234 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: servicedirectory, automerge, cla: yes, context: full

#236 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: servicedirectory, automerge, cla: yes

#237 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: servicedirectory, automerge, cla: yes

#238 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: servicedirectory, automerge, cla: yes, context: full

#239 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: api: servicedirectory, automerge, cla: yes, context: full, samples

#241 feat: promote to 1.0.0
  .repo-metadata.json
Labels: api: servicedirectory, automerge, cla: yes

#243 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: servicedirectory, automerge, cla: yes
