Repository googleapis/java-servicedirectory, pull requests merged in 2021-02, with the labels that each got.

#289 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: servicedirectory, cla: yes, context: partial

#290 build(java): update autorelease branch name check
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: servicedirectory, automerge, cla: yes, context: full

#291 chore: Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: automerge, cla: yes, context: full

#295 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: servicedirectory, automerge, cla: yes

#294 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: servicedirectory, automerge, cla: yes, context: full

#274 feat: update java samples to v1
  samples/snippets/src/main/java/com/example/servicedirectory/EndpointsCreate.java
  samples/snippets/src/main/java/com/example/servicedirectory/EndpointsDelete.java
  samples/snippets/src/main/java/com/example/servicedirectory/NamespacesCreate.java
  samples/snippets/src/main/java/com/example/servicedirectory/NamespacesDelete.java
  samples/snippets/src/main/java/com/example/servicedirectory/Quickstart.java
  samples/snippets/src/main/java/com/example/servicedirectory/ServicesCreate.java
  samples/snippets/src/main/java/com/example/servicedirectory/ServicesDelete.java
  samples/snippets/src/main/java/com/example/servicedirectory/ServicesResolve.java
  samples/snippets/src/test/java/com/example/servicedirectory/EndpointsTests.java
  samples/snippets/src/test/java/com/example/servicedirectory/NamespacesTests.java
  samples/snippets/src/test/java/com/example/servicedirectory/ServicesTests.java
Labels: api: servicedirectory, automerge, cla: yes, samples

#280 feat: added support for test cases and agent validation
  google-cloud-servicedirectory/src/test/java/com/google/cloud/servicedirectory/v1/RegistrationServiceClientTest.java
  synth.metadata
Labels: api: servicedirectory, automerge, cla: yes, context: full

#301 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  google-cloud-servicedirectory/src/test/java/com/google/cloud/servicedirectory/v1/RegistrationServiceClientTest.java
  synth.metadata
Labels: api: servicedirectory, automerge, cla: yes, context: partial

#303 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: servicedirectory, automerge, cla: yes, context: full

#304 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: api: servicedirectory, automerge, cla: yes, context: full

#305 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: servicedirectory, automerge, cla: yes, context: full

#300 chore: update gapic-generator-java to 0.0.20
  google-cloud-servicedirectory/src/main/java/com/google/cloud/servicedirectory/v1/LookupServiceClient.java
  google-cloud-servicedirectory/src/main/java/com/google/cloud/servicedirectory/v1/RegistrationServiceClient.java
  google-cloud-servicedirectory/src/main/java/com/google/cloud/servicedirectory/v1/package-info.java
  google-cloud-servicedirectory/src/main/java/com/google/cloud/servicedirectory/v1/stub/GrpcLookupServiceStub.java
  google-cloud-servicedirectory/src/main/java/com/google/cloud/servicedirectory/v1/stub/GrpcRegistrationServiceStub.java
  google-cloud-servicedirectory/src/main/java/com/google/cloud/servicedirectory/v1beta1/LookupServiceClient.java
  google-cloud-servicedirectory/src/main/java/com/google/cloud/servicedirectory/v1beta1/RegistrationServiceClient.java
  google-cloud-servicedirectory/src/main/java/com/google/cloud/servicedirectory/v1beta1/package-info.java
  google-cloud-servicedirectory/src/main/java/com/google/cloud/servicedirectory/v1beta1/stub/GrpcLookupServiceStub.java
  google-cloud-servicedirectory/src/main/java/com/google/cloud/servicedirectory/v1beta1/stub/GrpcRegistrationServiceStub.java
  google-cloud-servicedirectory/src/test/java/com/google/cloud/servicedirectory/v1/MockLookupServiceImpl.java
  google-cloud-servicedirectory/src/test/java/com/google/cloud/servicedirectory/v1/MockRegistrationServiceImpl.java
  google-cloud-servicedirectory/src/test/java/com/google/cloud/servicedirectory/v1beta1/MockLookupServiceImpl.java
  google-cloud-servicedirectory/src/test/java/com/google/cloud/servicedirectory/v1beta1/MockRegistrationServiceImpl.java
  synth.metadata
Labels: api: servicedirectory, automerge, cla: yes, context: partial

#309 chore: regenerate with gapic-generator-java v0.0.21 with gapic_metadata.json
  google-cloud-servicedirectory/src/main/java/com/google/cloud/servicedirectory/v1/RegistrationServiceClient.java
  google-cloud-servicedirectory/src/main/java/com/google/cloud/servicedirectory/v1/gapic_metadata.json
  google-cloud-servicedirectory/src/main/java/com/google/cloud/servicedirectory/v1beta1/gapic_metadata.json
  synth.metadata
Labels: api: servicedirectory, cla: yes, context: partial

#312 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: servicedirectory, automerge, cla: yes

#313 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: servicedirectory, automerge, cla: yes

#315 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: servicedirectory, automerge, cla: yes

#321 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: servicedirectory, automerge, cla: yes
