Repository googleapis/java-servicedirectory, pull requests merged in 2021-05, with the labels that each got.

#382 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: servicedirectory, automerge, cla: yes, context: none

#383 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: servicedirectory, automerge, cla: yes

#385 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: servicedirectory, automerge, cla: yes, context: full

#391 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: servicedirectory, automerge, cla: yes

#395 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: servicedirectory, automerge, cla: yes

#396 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: servicedirectory, automerge, cla: yes, context: full

#397 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: servicedirectory, automerge, cla: yes

#399 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: servicedirectory, automerge, cla: yes

#384 chore: convert to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/workflows/ci.yaml
  .kokoro/release/publish_javadoc11.sh
  google-cloud-servicedirectory-bom/pom.xml
  google-cloud-servicedirectory/pom.xml
  owlbot.py
  pom.xml
  synth.py
  versions.txt
Labels: api: servicedirectory, automerge, cla: yes

#408 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: servicedirectory, automerge, cla: yes

#413 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: servicedirectory, automerge, cla: yes

#414 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: servicedirectory, automerge, cla: yes

#416 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: servicedirectory, automerge, cla: yes
